name: Build and Publish Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ryo-discord-bot
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.CR_PAT }}

      - name: Get Image ID
        id: get_image_id
        run: |
          image_id=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          echo "lowercase_id=$(echo $image_id | tr '[A-Z]' '[a-z]')" >> $GITHUB_OUTPUT
          echo "short-ref=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ${{ steps.get_image_id.outputs.lowercase_id }}:latest
            ${{ steps.get_image_id.outputs.lowercase_id }}:${{ steps.get_image_id.outputs.short-ref }}